### ISSUE TITLE
App Shell + Island + Next.js, how?

### ISSUE THREAD

**Issue by mtt87** [trulia/islands-talk#1]
Hi, I've seen your great talk at ZEIT day and I'm curious to understand if you are using nginx or another proxy to work with next zones and mostly interested to know how App Shell and Island code and Next.js work together.

i.e. how are they imported / coupled to each other and how Next.js itself can import and "consume" both of them. 

Thank you 😄

**Comment by alexindigo** [comment]
Thank you for your interest.

We do use nginx as part of our Kubernetes setup,
and it does perform routing between islands (zones).

For more details let's move our conversation here, to have it in more interactive fashion.
https://gitter.im/trulia/islands-talk

Thank you.
